# syntax=docker/dockerfile:experimental

FROM node:10-alpine AS node-builder-dev

EXPOSE 3000
WORKDIR /var/www

RUN --mount=type=cache,id=apk,sharing=locked,target=/var/cache/apk ln -vs /var/cache/apk /etc/apk/cache && \
    apk add --update \
    curl \
    git \
    jq \
    make \
    python

CMD npm run build && \
    npm watch
